"""Post-Drafting Toxic Framing and Slang Detector.

Verifies that no incel slang, dysmorphic fatalism, or banned practices
survived or were generated by the LLM drafting step.
"""

from typing import Tuple, List
from src.schemas.pipeline_state import ArticleDraft
from src.safety.triage import TOXIC_SUBCLUTURE_TROPES, PROHIBITED_PATTERNS, _normalize_text


class ToxicSlangDetector:
    """Scans completed draft text for prohibited words and dysmorphic framing."""

    @staticmethod
    def scan(draft: ArticleDraft) -> Tuple[bool, List[str]]:
        corpus = (
            draft.title + " " +
            draft.scientific_summary + " " +
            " ".join(draft.actionable_protocol) + " " +
            " ".join(draft.contraindications) + " " +
            " ".join(f"{item.question} {item.answer}" for item in draft.structured_faq)
        )
        normalized = _normalize_text(corpus)
        violations: List[str] = []

        # Check toxic tropes
        for trope in TOXIC_SUBCLUTURE_TROPES:
            if _normalize_text(trope) in normalized:
                violations.append(f"Detected prohibited subculture trope: '{trope}'")

        # Check banned practices
        for pattern in PROHIBITED_PATTERNS:
            for kw in pattern["keywords"]:
                if _normalize_text(kw) in normalized:
                    violations.append(f"Detected prohibited physical practice in draft: '{kw}' [{pattern['id']}]")

        passed = len(violations) == 0
        return passed, violations
