"""Post-Drafting Toxic Framing and Slang Detector.

Verifies that no incel slang, dysmorphic fatalism, or banned practices
survived or were generated by the LLM drafting step.
"""

from typing import Tuple, List
from src.schemas.pipeline_state import ArticleDraft
from src.safety.triage import (
    TOXIC_SUBCLUTURE_TROPES,
    PROHIBITED_PATTERNS,
    _normalize_text,
    _compact_alphanumeric,
    check_banned_topic,
)


class ToxicSlangDetector:
    """Scans completed draft text for prohibited words, obfuscated slang, and dysmorphic framing."""

    @staticmethod
    def scan(draft: ArticleDraft) -> Tuple[bool, List[str]]:
        corpus = (
            draft.title + " " +
            draft.scientific_summary + " " +
            " ".join(draft.actionable_protocol) + " " +
            " ".join(draft.contraindications) + " " +
            " ".join(f"{item.question} {item.answer}" for item in draft.structured_faq)
        )
        normalized = _normalize_text(corpus)
        compact = _compact_alphanumeric(corpus)
        violations: List[str] = []

        # 1. Check toxic tropes (normalized and compact space-stripped representations)
        for trope in TOXIC_SUBCLUTURE_TROPES:
            norm_trope = _normalize_text(trope)
            compact_trope = _compact_alphanumeric(trope)
            if norm_trope in normalized or compact_trope in compact:
                violations.append(f"Detected prohibited subculture trope: '{trope}'")

        # 2. Check banned practices (normalized and compact)
        for pattern in PROHIBITED_PATTERNS:
            for kw in pattern["keywords"]:
                norm_kw = _normalize_text(kw)
                compact_kw = _compact_alphanumeric(kw)
                if norm_kw in normalized or compact_kw in compact:
                    violations.append(f"Detected prohibited physical practice in draft: '{kw}' [{pattern['id']}]")

        # 3. Comprehensive check on individual elements using fuzzy / homoglyph triage logic
        elements_to_check = (
            [draft.title, draft.scientific_summary] +
            draft.actionable_protocol +
            draft.contraindications +
            [f"{item.question} {item.answer}" for item in draft.structured_faq]
        )
        for elem in elements_to_check:
            is_banned, matched_pat, matched_phrase = check_banned_topic(elem)
            if is_banned and matched_pat:
                viol_msg = f"Detected prohibited practice/trope in draft: '{matched_phrase}' [{matched_pat.get('id', 'PROHIBITED')}]"
                if viol_msg not in violations:
                    violations.append(viol_msg)

        passed = len(violations) == 0
        return passed, violations
